FROM python:3.12-slim

# Set the working (current) directory
WORKDIR /app

# Set environment variables, this isn't really necessary for this example
ENV PYTHONPATH=/app

# Copy project files from current directory into /app
COPY . /app

# Upgrade pip itself
RUN pip install --upgrade pip

# Install Numpy and PyTorch with GPU support
RUN pip install --no-cache-dir numpy torch --extra-index-url https://download.pytorch.org/whl/cu118

# Run the application
CMD ["python", "app.py"]